language: python

python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install pytest
  - pip install codeclimate-test-reporter
  - pip install pytest-cov

# command to run tests
script: python -m pytest --cov

after_sucess:
  - CODECLIMATE_REPO_TOKEN=243d70ef2e24b4344d6ede6231230e3f001bed84f1e9bc0bdcfbc99d00ddb43d codeclimate-test-reporter
